services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: avecrm
      POSTGRES_USER: ave
      POSTGRES_PASSWORD: avepwd
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    command: sh -c "./scripts/init-perms.sh && php-fpm"
    depends_on: [db, redis]

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./backend:/var/www/html:ro          # ‚Üê Laravel code visible to nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on: [backend-php]

  adminer:
    image: adminer:4
    restart: unless-stopped
    environment:
      # Zorgt dat 'db' (jouw Postgres service) voorgeselecteerd staat
      ADMINER_DEFAULT_SERVER: db
      # Optioneel thema (others: flat, pepa-linha, etc.)
      ADMINER_DESIGN: dracula
    depends_on:
      - db
    ports:
      - "8081:8080"   # lokaal bereikbaar op http://localhost:8081
  

volumes:
  dbdata:
